// app/layout.js (or wherever your layout file is located)
import "./globals.css";
import Footer from "@/components/homepage/footer";
import Navbar from "@/components/homepage/navbar";
import Head from "next/head";

export const metadata = {
  title: "PICTOREAL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={`antialiased bg-[url('/homepage/bg.svg')] bg-repeat`}>
        <Navbar />
        <div className="grid grid-cols-12 gap-4">
          <main className="col-span-12 flex-grow">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
