import "./globals.css";
import Head from "next/head";
import LayoutWrapper from "../components/LayoutWrapper";

export const metadata = {
  title: "PICTOREAL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* <link rel="icon" href="/icon?<generated>" type="image/<generated>" sizes="<generated>" /> */}
        <link rel="apple-touch-icon" href="/icon?<generated>" type="image/<generated>" sizes="<generated>" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className="antialiased bg-[url('/homepage/bg.svg')] bg-repeat"> 
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}



